reactioncommerce/reaction-platform

- Makefile
Resolves: A sea of text
Type: **feature**
`make list` is a useful command to see the list of targets generated by the meta templating. Before this change the targets were space delimited. I'd been piping to `| xargs -n 1` manually. This automatically outputs them with linebreaks is easier to grok and work with on the command line. 
For example, to see targets directly related to hydra:
```
make list | grep hydra
```
1. Run `make list`
2. Behold the power.
> Delimit `make list` output with linebreaks

- Makefile
I use ed25519 ssh keys and the existing target only acknowledges rsa.
Use find and a glob to accept anything `~/.ssh/id_*.pub`
> feat: verify github ssh access but not ssh key details

- Makefile
- README.md
Resolves #9  
Type: **feature**
Main issue is current code always uses the default branch of each repo (some use master, some use develop) and many times users/developers will want to checkout a particular release which consists of particular tags of each subproject, or more generally will want to have a different branch checkout out than the default.
Related issue is we probably need some mechanism to coordinate versions of the subprojects that are tested together and known compatible/supported. This commit introduces a basic Makefile variable CSV structure to do that.
I followed the existing Makefile metaprogramming patterns to generate a `make checkout` and `make checkout-subproject*` templates.
This code has some pretty advanced Makefile metaprogramming that may …
> add checkout templated command

- config.mk
Resolves #26  
Impact: **major**  
Missing line continuation backslashes in the REQUIRED_SOFTWARE variable.
Add backslashes where needed.
`make dependencies` now works without error
> Fix syntax of dependency variable definition

- config.mk
Type: **feature**
We will be using a network `streams.reaction.localhost` for streaming infrastructure used by some new feature development. Add this network to the list so reaction-platform can create it during setup.
> Add streams.reaction.localhost network

- config.mk
Resolves #32 
The issue describes certain make targets failing, with a theory that a difference in syntax support between make 3.81 and later being the root cause.
Don't use `=` when defining multiline variables.
N/A
* Basic manual smoke testing on linux
* Basic manual smoke testing on a mac with make v3.81
```
make network-create
27d78333a74304ceb1c93ef6978d7677a96263c383e649a53027a1f72822084d
d714d825397e9b2d5f341b0d44341acc92895f221644a2b02989ecfba3a88330
2ec11658c2a73df8df5c9ea3f4a619ff048a7487ed34978e3211de686a63b7a0
```
> fix: Avoid old make version multiline var syntax

- Makefile
Resolves #37
Impact: **critical**  
Running `make` without any additional arguments on a fresh clone of `reaction-platform` is equivalent to running `make init`
The `init` template looks like this:
```sh
define init-template
init-$(1): $(1) network-create prebuild-$(1) build-$(1) post-build-$(1) start-$(1) post-project-start-$(1)
endef
$(foreach p,$(SUBPROJECTS),$(eval $(call init-template,$(p))))
```
the `clone` template looks like this
```
define git-clone-template
$(2):
git clone "$(1)" "$(2)"
endef
```
My understanding is that the `$(1)` variable in the init template ends up running clone defined as `$(2)` in the clone template.
The `init` template does _not_ run the `checkout` template. 
Until recently, we used the `master` branch as default for all projects which …
> fix: checkout git ref during init

- Makefile
Resolves #43  
Impact: **breaking**  
There was a missing semicolon in the clone target `$(2)` and when we rewrote the clone target to include checkout, the directory to `cd` into was typoed.
Adds missing semicolon to prevent unexpected end of file.
Changes checkout directory from `$(1)` which is the git url to `$(2)` which is the project/repo name.
n/a
1. Run `make` on a fresh project. Test with default branches and custom using `config.local.mk`
> fix: missing semicolon and correct checkout directory

- CHANGELOG.md
- config.mk
This is our first official release candidate for this project.
I've set the `config.mk` file to use the release tags coordinated across the reaction platform. 
- [reaction-next-starterkit](https://github.com/reactioncommerce/reaction-next-starterkit/pull/483)
- [reaction](https://github.com/reactioncommerce/reaction/pull/4922)
- [reaction-hydra](https://github.com/reactioncommerce/reaction-hydra/pull/11)
The QA for release of this version of `reaction-platform` should involve testing that the projects are compatible and work together. 
Running this release-candidate branch of `reaction-platform` should also set up the associated release branch for each of the projects in the platform. These are the versions that should be tested - that they are performing as expected, and that they are …
> Release 2.0.0 rc.9

- CHANGELOG.md
- config.mk
This is our second official release candidate for this project.
The `config.mk` file to use the release tags coordinated across the reaction platform. 
- [reaction-next-starterkit](https://github.com/reactioncommerce/reaction-next-starterkit/pull/512)
- [reaction](https://github.com/reactioncommerce/reaction/pull/5016)
- [reaction-hydra](https://github.com/reactioncommerce/reaction-hydra/pull/12)
The QA for the release of this version of `reaction-platform` should involve testing that the projects are compatible and work together. 
Running this release-candidate branch of `reaction-platform` should also set up the associated release branch for each of the projects in the platform. These are the versions that should be tested - that they are performing as expected, and that they are …
> v2.0.0-rc.10

- CHANGELOG.md
- config.mk
This is our third official release candidate for this project.
The `config.mk` file to use the release tags coordinated across the reaction platform. 
- [reaction-next-starterkit](https://github.com/reactioncommerce/reaction-next-starterkit/pull/517)
- [reaction](https://github.com/reactioncommerce/reaction/pull/5049)
- [reaction-hydra](https://github.com/reactioncommerce/reaction-hydra/pull/13)
The QA for the release of this version of `reaction-platform` should involve testing that the projects are compatible and work together. 
Running this release-candidate branch of `reaction-platform` should also set up the associated release branch for each of the projects in the platform. These are the versions that should be tested - that they are performing as expected, and that they are …
> Release v2.0.0-rc.11

- README.md
- config.mk
Impact: **breaking|critical**  
Type: **chore**
We want to rename our storefront from "reaction-next-starterkit" to "example-storefront", to do this we need to update all references to that project/repo before we can officially change the name. 
Updated the git repo name in the `config.mk` file, updated all refs/links in the README
N/A
> chore: updated all reference of starterkit to example-storefront.

- CHANGELOG.md
- config.mk
This is our fourth official release candidate for this project.
The `config.mk` file to use the release tags coordinated across the reaction platform. 
- [example-storefront](https://github.com/reactioncommerce/example-storefront/pull/547)
- [reaction](https://github.com/reactioncommerce/reaction/pull/5259)
- [reaction-hydra](https://github.com/reactioncommerce/reaction-hydra/pull/20)
The QA for the release of this version of `reaction-platform` should involve testing that the projects are compatible and work together. 
Running this release-candidate branch of `reaction-platform` should also set up the associated release branch for each of the projects in the platform. These are the versions that should be tested - that they are performing as expected, and that they are compatible with …
> Release v2.0.0-rc.12 

- CHANGELOG.md
- config.mk
- https://github.com/reactioncommerce/reaction/pull/5409
- https://github.com/reactioncommerce/reaction-hydra/pull/22
- https://github.com/reactioncommerce/example-storefront/pull/557/
This is a minor versioning release coordinated with [Reaction](https://github.com/reactioncommerce/reaction), our [Example Storefront](https://github.com/reactioncommerce/example-storefront) and [reaction-hydra](https://github.com/reactioncommerce/reaction-hydra).
> release v2.1.0

- CHANGELOG.md
- config.mk
This is minor version update coordinated with [Reaction](https://github.com/reactioncommerce/reaction), our [Example Storefront](https://github.com/reactioncommerce/example-storefront) and [reaction-hydra](https://github.com/reactioncommerce/reaction-hydra).
> chore: bump version to v2.4.0

- CHANGELOG.md
- config.mk
This is minor version update coordinated with [Reaction](https://github.com/reactioncommerce/reaction), our [Example Storefront](https://github.com/reactioncommerce/example-storefront) and [reaction-hydra](https://github.com/reactioncommerce/reaction-hydra).
> chore: bump version to v2.5.0

- CHANGELOG.md
- config.mk
This is minor version update coordinated with [Reaction](https://github.com/reactioncommerce/reaction), our [Example Storefront](https://github.com/reactioncommerce/example-storefront) and [reaction-hydra](https://github.com/reactioncommerce/reaction-hydra)
> chore: bump to version 2.6.0

- CHANGELOG.md
- config.mk
This is minor version update coordinated with [Reaction](https://github.com/reactioncommerce/reaction), our [Example Storefront](https://github.com/reactioncommerce/example-storefront) and [reaction-hydra](https://github.com/reactioncommerce/reaction-hydra).
> chore: bump to version 2.7.0

- CHANGELOG.md
- config.mk
This is a major update to keep this project in sync with
[reaction v3.0.0-alpha](https://github.com/reactioncommerce/reaction),
[example-storefront v3.0.0-alpha](https://github.com/reactioncommerce/example-storefront),
and [reaction-platform v3.0.0-alpha](https://github.com/reactioncommerce/reaction-platform).
> chore: release v3.0.0-alpha

- CHANGELOG.md
- config.mk
Reverts reactioncommerce/reaction-platform#82
Reverting the merge of `release-3.0.0-alpha` into master. Master should stay on `2.x` until the official `3.0` release.
> Revert "chore: release v3.0.0-alpha"

- CHANGELOG.md
- config.mk
This alpha release bumps the versions of
[reaction](https://github.com/reactioncommerce/reaction/tree/v3.0.0-alpha.2)
and [example-storefront](https://github.com/reactioncommerce/example-storefront/tree/v3.0.0-alpha.2)
to their latest alpha releases.
> chore: release v3.0.0-alpha.2
